config/routes.rb
Rails.application.routes.draw do
	root 'fale_mais#result'
	resources :fale_mais
	resources :rates
	get 'result' => 'fale_mais#result'  # Rota para GET Result
	post 'result' => 'fale_mais#result' # Rota para POST formulario Calculadora

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fale_mai.rb
class FaleMai < ApplicationRecord
	has_many :rate

	def calculaPlano(minutos, valorMinuto, minutoFaleMais)
		if(minutos <= minutoFaleMais)
			return 0
		end

		minutosExcedentes = minutos - minutoFaleMais # Descobre os Excendentes

		valorTaxaSoma = valorMinuto * 0.1

		valorMinuto = valorMinuto + valorTaxaSoma

		valorFaleMais = minutosExcedentes * valorMinuto

		return valorFaleMais

	end

	def calculaSemPlano(minutos, valorMinuto)

		valorSemFaleMais = minutos * valorMinuto

		return valorSemFaleMais
	end


end	

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :fale_mai, :optional => true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fale_mais_controller.rb
class FaleMaisController < ApplicationController 
  before_action :set_fale_mai, only: [:show, :edit, :update, :destroy]

  # GET /fale_mais
  # GET /fale_mais.json
  def index
    @fale_mai = FaleMai.all
  end

  # GET /fale_mais/1
  # GET /fale_mais/1.json
  def show
  end

  # GET /fale_mais/new
  def new
    @fale_mai = FaleMai.new
  end

  # /fale_mais/result
  def result    
   @fale_mai =  FaleMai.all
   @error= false

    if request.post? # Se consulta por post, faz a busca, de acordo com a Origin/Destiny/Plano.
      begin 
        @rates = Rate.where(origin: params['tax_origem'], destiny: params['tax_destino']).take
        @faleMais = FaleMai.new

       @comFaleMais = @faleMais.calculaPlano(params['minutos'].to_i, @rates.price_per_minute.to_f, params['fm_name'].to_i) # Resgata valor com Fale Mais
       @semFaleMais = @faleMais.calculaSemPlano(params['minutos'].to_i, @rates.price_per_minute.to_f) # Resgata valor sem Fale Mais
     rescue  
      @error = true;
    end

  end

end

  # GET /fale_mais/1/edit
  def edit
  end

  # POST /fale_mais
  # POST /fale_mais.json
  def create
    @fale_mai = FaleMai.new(fale_mai_params)

    respond_to do |format|
      if @fale_mai.save
        format.html { redirect_to @fale_mai, notice: 'Fale mai was successfully created.' }
        format.json { render :show, status: :created, location: @fale_mai }
      else
        format.html { render :new }
        format.json { render json: @fale_mai.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fale_mais/1
  # PATCH/PUT /fale_mais/1.json
  def update
    respond_to do |format|
      if @fale_mai.update(fale_mai_params)
        format.html { redirect_to @fale_mai, notice: 'Fale mai was successfully updated.' }
        format.json { render :show, status: :ok, location: @fale_mai }
      else
        format.html { render :edit }
        format.json { render json: @fale_mai.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fale_mais/1
  # DELETE /fale_mais/1.json
  def destroy
    @fale_mai.destroy
    respond_to do |format|
      format.html { redirect_to fale_mais_url, notice: 'Fale mai was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fale_mai
      @fale_mai = FaleMai.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fale_mai_params
      params.require(:fale_mai).permit(:name, :minute)
    end
  end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: 'Rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:origin, :destiny, :price_per_minute)
    end
end

app/helpers/aplicacao_helper.rb
module AplicacaoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fale_mais_helper.rb
module FaleMaisHelper

end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/fale_mais/_calc.html.erb
<aside>
	<div class="inner-calc">
		<h3>Calculadora FaleMais - Telzir</h3>
		<h4>Saiba quanto você economizou com nosso plano Fale Mais!</h4>

		<%= form_tag("/result", method: "post") do %>
		
		<div class="input-out number-out">
			<%= label_tag('tax_origem', "DDD Origem") %>
			<%= number_field_tag('tax_origem', nil, class: 'input-ddd-calc') %>
		</div>

		<div class="input-out number-out">
			<%= label_tag('tax_destino', "DDD Destino") %>
			<%= number_field_tag('tax_destino', nil, class: 'input-ddd-calc') %>
		</div>

		<div class="input-out number-out">
			<%= label_tag('minutos', "Tempo") %>
			<%= number_field_tag('minutos', nil, class: 'input-min-calc') %>
		</div>

		<div class="input-out">
			<%= label_tag('fm_name', "Escolha o Plano:") %>
			<%= select_tag 'fm_name', options_for_select(@fale_mai.collect{ |u| [u.name, u.minute] }) %>
		</div>

		<%= submit_tag("Calcular", class: 'input-btn-calc') %>
		<% end %>

	</div>
</aside>

app/views/fale_mais/_form.html.erb
<%= form_with(model: fale_mai, local: true) do |form| %>
  <% if fale_mai.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fale_mai.errors.count, "error") %> prohibited this fale_mai from being saved:</h2>

      <ul>
      <% fale_mai.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :minute %>
    <%= form.number_field :minute %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fale_mais/edit.html.erb
<h1>Editing Fale Mai</h1>

<%= render 'form', fale_mai: @fale_mai %>

<%= link_to 'Show', @fale_mai %> |
<%= link_to 'Back', fale_mais_path %>

app/views/fale_mais/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fale Mais</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Minute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fale_mai.each do |fale_mai| %>
      <tr>
        <td><%= fale_mai.name %></td>
        <td><%= fale_mai.minute %></td>
        <td><%= link_to 'Show', fale_mai %></td>
        <td><%= link_to 'Edit', edit_fale_mai_path(fale_mai) %></td>
        <td><%= link_to 'Destroy', fale_mai, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fale Mais', new_fale_mai_path %>

app/views/fale_mais/new.html.erb
<h1>New Fale Mai</h1>

<%= render 'form', fale_mai: @fale_mai %>

<%= link_to 'Back', fale_mais_path %>

app/views/fale_mais/result.html.erb
<%= render 'calc' %>

<% if !@error %> 

<% if @faleMais %>


<div class="result result-success">
	<div class="inner-display">
		<h1>Veja o quanto economizou</h1>
		<div class="result-out">
			<div class="result-inner com-fale-mais">
				<p><strong>Com Fale Mais:</strong></p>
				<p><strong><%= number_to_currency(@comFaleMais, unit: 'R$', separator: ',', delimiter: '.') %></strong></p>
			</div>
			<div class="result-inner sem-fale-mais">
				<p>Sem Fale Mais:</p>
				<p><%= number_to_currency(@semFaleMais, unit: 'R$', separator: ',', delimiter: '.') %></p>
			</div>
		</div>
	</div>
</div>

<% else %>

<div class="initial-display">
	<div class="inner-display">
		<h1>TELZIR </h1> 
		<h3>Ficou mais fácil saber como economizar</h3>
		<p>Utilize a calculadora ao lado e descubra</p>
	</div>
</div>

<% end %>
<% else %>
<div class="result result-error">
	<div class="inner-display">
		<p>Não encontramos em nosso banco de dados a combinação dos DDDs informados.</p>
		<p>Tente novamente.</p>
	</div>
</div>
<% end %>

<div class="footer">
	<div class="menu">
		<%= link_to "Cadastrar Fale Mais", fale_mais_path %>
		<%= link_to "Cadastrar DDDs e Taxas", rates_path %>

	</div>
	<div class="assinatura">
		Desafio para Vizir - Wallace Petrucci Neves
	</div>

</div>

app/views/fale_mais/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fale_mai.name %>
</p>

<p>
  <strong>Minute:</strong>
  <%= @fale_mai.minute %>
</p>

<%= link_to 'Edit', edit_fale_mai_path(@fale_mai) %> |
<%= link_to 'Back', fale_mais_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vizir</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <section class="section-main">
    <%= yield %>
  </section>
</body>
</html>

app/views/rates/_form.html.erb
<%= form_with(model: rate, local: true) do |form| %>
  <% if rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :origin %>
    <%= form.number_field :origin %>
  </div>

  <div class="field">
    <%= form.label :destiny %>
    <%= form.number_field :destiny %>
  </div>

  <div class="field">
    <%= form.label :price_per_minute %>
    <%= form.text_field :price_per_minute %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rates</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destiny</th>
      <th>Price per minute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rates.each do |rate| %>
      <tr>
        <td><%= rate.origin %></td>
        <td><%= rate.destiny %></td>
        <td><%= rate.price_per_minute %></td>
        <td><%= link_to 'Show', rate %></td>
        <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
        <td><%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New Rate</h1>
<%= render 'form', rate: @rate %>


<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @rate.origin %>
</p>

<p>
  <strong>Destiny:</strong>
  <%= @rate.destiny %>
</p>

<p>
  <strong>Price per minute:</strong>
  <%= @rate.price_per_minute %>
</p>

<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>